package com.health_data_analysis.backend.service;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.UUID;

import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

@Component
public class FileStorage {

    private final Path root = Path.of("uploads");   // or S3/MinIO client in production

    public FileStorage() throws IOException {
        Files.createDirectories(root);
    }

    /** Saves the raw upload under a random UUID name, returns the storage key. */
    public String store(MultipartFile file) throws IOException {
        String key = UUID.randomUUID() + ".csv";
        Files.copy(file.getInputStream(), root.resolve(key),
                   StandardCopyOption.REPLACE_EXISTING);
        return key;
    }

    public InputStream load(String storageKey) throws IOException {
        // storageKey was generated by us (UUID), but validate anyway — never
        // trust anything that could touch a filesystem path
        if (!storageKey.matches("[0-9a-f-]{36}\\.csv")) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        return Files.newInputStream(root.resolve(storageKey));
    }
}
